### ISSUE TITLE
Confusing Language Around "open-source wearable art"

### ISSUE THREAD

**Issue by abetusk** [azzeloof/osj#37]
From the home page of [open.jewelry](https://open.jewelry/), there line under the "Welcome to OpenJewelry!" line that reads:

> The internet's home for open-source wearable art of all kinds

As of this writing, the three examples ([snowflake brooch by adam](https://open.jewelry/jewelry/3/), [function ring by  adam](https://open.jewelry/jewelry/2/) and [organic bracelet by adam](https://open.jewelry/jewelry/1/)) are all not generally considered open source as they have a "non-commercial" clause attached to their design files.

"Open Source" has a generally accepted meaning of being able to re-use the digital artifacts for commercial purposes. The [OSI](https://opensource.org/osd) and Wikipedia's entry on [open-source licensing](https://en.wikipedia.org/wiki/Open-source_license) both articulate that commercial re-use is a (generally accepted) requirement of an "open source" license.

The licensing for the website and verbiage on the Open Jewelry website and framework is very clearly "open source" by the commonly accepted definition, but allowing the digital artifacts hosted on the website to be non open source creates confusion, especially when Open Jewelry indicates it's meant to be the home of "open source wearable art".

Projects like Thingiverse don't claim to have all of their artifacts as "open source". Thingiverse allows a variety of options for licensing, including for commercial re-use and for non-commercial re-use.

Projects like [OpenGameArt](https://opengameart.org/) are clear about being "open source" and require digital artifacts deposited on the site to be available for commercial re-use. [FreeSewing](https://freesewing.org/docs/faq/commercial-use/) has all of its content, including the sewing patterns, under a CC-BY4.0 license.

The icon for Open Jewelry creates further confusion as it's reminiscent of the Open Source Hardware logo. The [Open Source Hardware Association](https://www.oshwa.org/definition/) articulates requirements of design files to meet their "open source" standards:

> Open source hardware is hardware whose design is made publicly available so that anyone can study, modify, distribute, make, and sell the design or hardware based on that design.

If you allow for non-commercial licenses for the digital artifacts on the site, please change the "Open Jewelry" to something less confusing. The usual term for publishing digital artifacts without an open source license is "source available" and is more appropriate to the site as it stands now.

If you continue to use the name "Open Jewelry", please change the policy to only allow digital artifacts that are actually open source and, specifically, discontinue the option that allows digital artifacts to be placed under a non-commercial license.

**Comment by azzeloof** [comment]
This is a fantastic point, thank you for bringing it to my attention.
This warrants more consideration, but for the time being, I've changed the license of my pieces to one compatible with OSHW standards (CC-BY-SA 4.0), removed the incompatible licenses, and added GPLv3 (which I had been meaning to do already)
I will also be reviewing other license options to add to the site. The user also has the option to use any compatible license by linking to it in an attached project repository.
